# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='creation_date',
            new_name='upload_date',
        ),
    ]
