# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import photo_gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0002_auto_20170116_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='icon',
            field=models.ImageField(blank=True, upload_to=photo_gallery.models.user_directory_path),
        ),
    ]
