# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-17 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0003_imagemodel_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'permissions': (('view_image', 'View image'),)},
        ),
    ]
